### ISSUE TITLE
Jobs error

### ISSUE THREAD

**Issue by MesziPeti** [esx-framework/esx_jobs#1]
Hi!
For 1-2 jobs, such as Fisherman, after I put on the work clothes and start the task, if I go to the marker, I get the error shown in the picture. Sorry for my poor English, I used a translator.
![Screenshot_71](https://user-images.githubusercontent.com/127037056/222968868-0c9102d9-dd98-4986-ba95-f840cf580b43.png)

Thank you

**Comment by CsokiHUN** [comment]
fixed in #16
