### ISSUE TITLE
problem with work zones

### ISSUE THREAD

**Issue by NitroX28** [esx-framework/esx_jobs#103]
hi, when i want to work i need to come back between 3 and 5 time in the work zone because it's don't transform , for example if i want to transform oil to fuel , the zone will be functional after 5 come backs 
so i don't know what is the problem

**Comment by Duqino** [comment]
I think the location of the marker and the location that will start the job are not at the same location in the world.

Im having the same issue.

**Comment by MintKind** [comment]
I am encountering the same issue. Haven't found a fix yet.

**Comment by Titas-** [comment]
I had this problem, and found out what's the problem.
Basically ESX updates location every Xms(Configured in config), AND if location changes more than 10.
I changed location difference to 3 and it works as a charm.
If someone need help with this you can contact me on DC Titas#5726

**Comment by phpadmin1** [comment]
Does

> I had this problem, and found out what's the problem.
> Basically ESX updates location every Xms(Configured in config), AND if location changes more than 10.
> I changed location difference to 3 and it works as a charm.
> If someone need help with this you can contact me on Discord Titas#5726
> 
> 1. To fix it change your location update rate to around 500(ms) (it works for me)
>    In config.lua change `Config.CoordsSyncInterval` to 500
> 2. In ESX -> Client -> main.lua
>    Change `if distance > 10 then` to `if distance > 3 then`
>    That will make ESX update location if it changes more than 3 units.

Its Safe to do that 500 milli and changes more than 3 units?

**Comment by bakerzone** [comment]
Has anyone else actually got these to work, I've modified my config files as per the above and I cannot get any of these to recognize that I am actually anywhere near the location that it should start the register call back command?

**Comment by Duqino** [comment]
They fixed it in a newer version of ESX. But i cant run the newest because of bugs so i changed it myself.

es_extended\client

Bottem of the code remove the existing part and place this instead of it. I did not right the code. ElPumpo did. You can also remove the option in the config file.

`-- Update current player coords
Citizen.CreateThread(function()
	-- wait for player to restore coords
	while not isLoadoutLoaded do
		Citizen.Wait(1000)
	end

	local previousCoords = vector3(ESX.PlayerData.coords.x, ESX.PlayerData.coords.y, ESX.PlayerData.coords.z)

	while true do
		Citizen.Wait(1000)
		local playerPed = PlayerPedId()

		if DoesEntityExist(playerPed) then
			local playerCoords = GetEntityCoords(playerPed)
			local distance = #(playerCoords - previousCoords)

			if distance > 1 then
				previousCoords = playerCoords
				local playerHeading = ESX.Math.Round(GetEntityHeading(playerPed), 1)
				local formattedCoords = {x = ESX.Math.Round(playerCoords.x, 1), y = ESX.Math.Round(playerCoords.y, 1), z = ESX.Math.Round(playerCoords.z, 1), heading = playerHeading}
				TriggerServerEvent('esx:updateCoords', formattedCoords)
			end
		end
	end
end)`

**Comment by JoeyMBrown** [comment]
Still experiencing this same issue.  Not experiencing it on local dev server, only live server.

**Comment by Titas-** [comment]
For linux users change `os.clock()` to `os.time()`

**Comment by mmod-max** [comment]
Tried os.time() in server main.lua - nothing.
Config.CoordsSyncInterval to 500ms in es_esxtended config worked! :)

**Comment by BrakingESX247** [comment]
I believe you have found a solution to the problem, if not open another issue. Feel free to make a Pull Request If you think you have fixed that and want to share it with others :)
