### ISSUE TITLE
Longer times than set.

### ISSUE THREAD

**Issue by Titas-** [esx-framework/esx_jobs#118]
If you are using Linux, and it takes way longer than set in config to get items, you need to change following stuff:
Change `os.clock()` to `os.time()`
Basically `os.clock()` works differently on Windows and Linux, and on Linux times are way longer.
While using `os.time()` on Linux shows that it works just like `os.clock()` on Windows

----------------------------------------

If someone need help with this you can contact me on Discord Titas#5726

**Comment by BrakingESX247** [comment]
Hello, please open a Pull Request on this, I was going to do so, but It's you that found about it, so I will let you do that :) Maybe add a config option?
