### ISSUE TITLE
Fisherman TUG not spawning

### ISSUE THREAD

**Issue by wipsjack** [esx-framework/esx_jobs#121]
Hi i use lastest esx_jobs and suit fisherman clothes but i dont spawn Tug

**Comment by BTNGaming** [comment]
Same issue here.

**Comment by Kings9555** [comment]
same

**Comment by Danny9865** [comment]
same

**Comment by GermanGaming** [comment]
yes i have the same issue

**Comment by BrakingESX247** [comment]
I believe #109 fixed that, If not, open a new issue.
