### ISSUE TITLE
Changing Job Grade through Script

### ISSUE THREAD

**Issue by FuryFight3r** [esx-framework/esx_jobs#122]
This isnt so much an issue, just lack of documentation and tutorials with most esx mods, but how can I change the players Job Grade through LUA scripting. I created a job script that has multiple roles and the grades act as the roles, IE 0 is a Cleaner, 1 is a Cashier, 2 is a Cook and 3 is a Delivery Driver. I have currently a menu that becomes active once you have the Specific job title, this allows you to choose what role you want to do. this is where I would put the part where it changes the players Job Grade according to their selection (the grades have no better or worse about them they are all the same, just different tasks). 
![Screenshot_5](https://user-images.githubusercontent.com/44615800/83881692-63328b80-a784-11ea-8ee6-019b561dac65.png)
![Screenshot_6](https://user-images.githubusercontent.com/44615800/83881702-66c61280-a784-11ea-9855-a0656ee2061a.png)

**Comment by BrakingESX247** [comment]
Hello, please refer to this https://esx-framework.github.io/, thank you.
