### ISSUE TITLE
No MYSQL table creators for ESX JOBS

### ISSUE THREAD

**Issue by Mansonjr** [esx-framework/esx_jobs#124]
Before someone answer with this link:

https://github.com/ESX-Org/esx_jobs/blob/master/esx_jobs.sql

It's only Insers, it not create tables with the propper structure.

Can this table creating being included in sql if they do not exist?

**Comment by BrakingESX247** [comment]
Not needed, as es_extended already creates this tables which is an essential to running this resource. Also, esx_addonaccount creates the 'addon_account' table, which is again essential to running this resource. Both are requirements.
