### ISSUE TITLE
SQL Error (1146): Table 'es_extended.jobs' doesn't exist

### ISSUE THREAD

**Issue by jimmy20000yt** [esx-framework/esx_jobs#137]
If anyone can help me pls answer this Issue!

**Comment by izio38** [comment]
Sad that people can't read a fucking manual 
https://github.com/esx-framework/esx_jobs#installation

**Comment by jimmy20000yt** [comment]
![image](https://user-images.githubusercontent.com/70151490/104218557-95584a00-5445-11eb-8a0f-83aa1bbacc8e.png)
 @izio38 I am new and I don't know so much think but when I run the file this appears!

**Comment by izio38** [comment]
You probably ran the sql file twice.

**Comment by jimmy20000yt** [comment]
the same

**Comment by jimmy20000yt** [comment]
![image](https://user-images.githubusercontent.com/70151490/104220201-ca659c00-5447-11eb-9253-95ccb439c9b6.png)
maybe is here the issue?

**Comment by izio38** [comment]
Into the addon_account table, the name is a primary key (cannot be inserted twice with the same name). So I think you already ran the script.

**Comment by jimmy20000yt** [comment]
Oh and now I have an error with the es_extended YAY but thx for the help man!
