### ISSUE TITLE
Crashing FiveM when walking into marker

### ISSUE THREAD

**Issue by Luci666MS** [esx-framework/esx_jobs#147]
i created a custom job. followed the format and then add a menu for that custom job inside client.lua. now I can't walk into a marker. Here are the modified/new files.

https://pastebin.com/KqHvuVKP I appended this code in main.lua
https://pastebin.com/DKWBmb1V this is the job.

**Comment by FreakOutModz** [comment]
Ask author, this is not esx_jobs.
