### ISSUE TITLE
Blips not showing correctly

### ISSUE THREAD

**Issue by justo19** [esx-framework/esx_jobs#19]
Any version after 1.8.5 has blip update issues. Blips do not update correctly when making a job change or starting the character from esx_multicharacter

**Comment by Gellipapa** [comment]
@justo19 Hi! Can you describe how we can reproduce this because I don't quite understand. So if you enter with esx_multicharacter what blip is not updated?

**Comment by justo19** [comment]
First of all sorry for my bad English. I have detected that when changing jobs with the esx_joblisting resource, the blips are not refreshed correctly. I have put print(playerJob) in the refreshBlips() function. I have seen that the job before the job I have chosen in the list appears. Example: If I have the miner job and I select the fueler job, it prints "miner"

**Comment by Gellipapa** [comment]
@TheFantomas Hi! Please check.

**Comment by justo19** [comment]
Line 211 -->   for jobKey, jobValues in pairs(Config.Jobs) do

Now I have tried adding just after this line located in the Main.lua (Client side) file, print(jobKey, jobValues) to see the table values ​​when I restart the script. I have seen that it does not always recognize all the jobs. 

I upload another video showing the values ​​in console:

https://youtu.be/Cn87xifTd3M

**Comment by Thekuca** [comment]
@justo19 Hey, could you please test it with this change #20 or download it from this [branch](https://github.com/esx-framework/esx_jobs/tree/testfix)

**Comment by justo19** [comment]
The problem remains exactly the same. I have also noticed that sometimes the blips are not displayed or are partially displayed. Example: The work blips appear but the cloakroom blip does not appear.

Sorry for the inconvenience. If it is necessary to provide more information, I will be willing to do it.

**Comment by justo19** [comment]
I have tried to gradually edit the script from version 1.8.5 to version 1.9.1 and now it works! It is possible that there was a problem in the local files, specifically in the es.lua file. However, I have not fully understood how it has been solved. Thank you so much.

**Comment by Gellipapa** [comment]
@justo19 We're glad it worked but could you please test it with 1.10.1 which is the latest and there have been changes in esx_job. Thank you very much in advance.

**Comment by justo19** [comment]
Oh excuse me, I have downloaded the latest version shown in public and it says 1.9.1 I guess it will be the version you mention. Works correctly. If you need anything else, let me know. Thank you so much

**Comment by justo19** [comment]
Sorry for the inconvenience. I thought I was using version 1.8.5 The version I was using was 1.1.0 which worked correctly. version 1.8.5 and the new version with the fixes still have a problem getting the blip table. I am using all dependencies to the latest released version

**Comment by TheFantomas** [comment]
> Sorry for the inconvenience. I thought I was using version 1.8.5 The version I was using was 1.1.0 which worked correctly. version 1.8.5 and the new version with the fixes still have a problem getting the blip table. I am using all dependencies to the latest released version

Hello,

We must rewrite this resource. Its a priority after the esx_property rewrite.

Thanks for bug report.

Best regards
ESX Director
@TheFantomas

**Comment by justo19** [comment]
Thank you very much for your attention. you are a great team!!

**Comment by Gellipapa** [comment]
@justo19 Hi! I understand it works now?
