### ISSUE TITLE
Cannot change job cloth

### ISSUE THREAD

**Issue by adminSTRP** [esx-framework/esx_jobs#25]
`SCRIPT ERROR: @esx_jobs/client/main.lua:51: attempt to index a nil value (local 'jobSkin')
ref (@esx_jobs/client/main.lua:51)
handler (@es_extended/client/modules/callback.lua:22)
SCRIPT ERROR: error object is not a string`

**Comment by Gellipapa** [comment]
@adminSTRP Hi! Thank you for report issue, i tested latest version and i can change clothes please retest.

**Comment by Gellipapa** [comment]
Hi! I tested if you have working clothes in db works perfectly. Please send me your job_grades table. 
![image](https://github.com/esx-framework/esx_jobs/assets/22717950/9d661d69-f0f2-402a-8091-85c76b7158be)
