### ISSUE TITLE
Job cloth not load for Fisherman & Fueler

### ISSUE THREAD

**Issue by jamesfill** [esx-framework/esx_jobs#76]
This issue is very simple, when i go to the cloakroom to change the uniform of job fisherman + Fueler is display nothing, no error show on terminal & F8 windows.

Anyone can help me ?

**Comment by bsdesire** [comment]
They're not defined in the database, check the entries on skin_male and skin_female, they should be empty

**Comment by BrakingESX247** [comment]
Hello, I believe the previous comment has your solution, if not, open another issue, thank you.
