### ISSUE TITLE
Cant delete boat.

### ISSUE THREAD

**Issue by Duqino** [esx-framework/esx_jobs#82]
Hello,

Im in need of help. I cant remove my boat for the fisher job

[![Screenshot from Gyazo](https://gyazo.com/b9c1352214093f7f3cc5f2fcac0c66c8/raw)](https://gyazo.com/b9c1352214093f7f3cc5f2fcac0c66c8)

>  -- Activate menu when player is inside marker
> Citizen.CreateThread(function()
> 	while true do
> 
> 		Citizen.Wait(1)
> 
> 		if PlayerData.job ~= nil and PlayerData.job.name ~= 'unemployed' then
> 			local zones = nil
> 			local job = nil
> 
> 			for k,v in pairs(Config.Jobs) do
> 				if PlayerData.job.name == k then
> 					job = v
> 					zones = v.Zones
> 				end
> 			end
> 
> 			if zones ~= nil then
> 				local coords      = GetEntityCoords(PlayerPedId())
> 				local currentZone = nil
> 				local zone        = nil
> 				local lastZone    = nil
> 
> 				for k,v in pairs(zones) do
> 					if GetDistanceBetweenCoords(coords, v.Pos.x, v.Pos.y, v.Pos.z, true) < v.Size.x then
> 						isInMarker  = true
> 						currentZone = k
> 						zone        = v
> 						break
> 					else
> 						isInMarker  = false
> 					end
> 				end
> 
> 				if IsControlJustReleased(0, Keys['E']) and not menuIsShowed and isInMarker then
> 					if onDuty or zone.Type == "cloakroom" or PlayerData.job.name == "reporter" then
> --->> 432						TriggerEvent('esx_jobs:action', job, zone)
> 					end
> 				end
> 
> 				-- hide or show top left zone hints
> 				if isInMarker and not menuIsShowed then
> 					hintIsShowed = true
> 					if (onDuty or zone.Type == "cloakroom" or PlayerData.job.name == "reporter") and zone.Type ~= "vehdelete" then
> 						hintToDisplay = zone.Hint
> 						hintIsShowed = true
> 					elseif zone.Type == "vehdelete" and (onDuty or PlayerData.job.name == "reporter") then
> 						local playerPed = PlayerPedId()
> 
> 						if IsPedInAnyVehicle(playerPed, false) then
> 							local vehicle = GetVehiclePedIsIn(playerPed, false)
> 							local driverPed = GetPedInVehicleSeat(vehicle, -1)
> 							local plate = GetVehicleNumberPlateText(vehicle)
> 							plate = string.gsub(plate, " ", "")
> 
> 							if playerPed == driverPed then
> 
> 								for i=1, #myPlate, 1 do
> 									if myPlate[i] == plate then
> 										hintToDisplay = zone.Hint
> 										break
> 									end
> 								end
> 
> 							else
> 								hintToDisplay = _U('not_your_vehicle')
> 							end
> 						else
> 							hintToDisplay = _U('in_vehicle')
> 						end
> 						hintIsShowed = true
> 					elseif onDuty and zone.Spawner ~= spawner then
> 						hintToDisplay = _U('wrong_point')
> 						hintIsShowed = true
> 					else
> 						if not isInPublicMarker then
> 							hintToDisplay = "no hint to display"
> 							hintIsShowed = false
> 						end
> 					end
> 				end
> 
> 				if isInMarker and not hasAlreadyEnteredMarker then
> 					hasAlreadyEnteredMarker = true
> 				end
> 
> 				if not isInMarker and hasAlreadyEnteredMarker then
> 					hasAlreadyEnteredMarker = false
> 					TriggerEvent('esx_jobs:hasExitedMarker', zone)
> 				end
> 			end
> 		end
> 	end
> end)

**Comment by BrakingESX247** [comment]
@Duqino Still having issues with that?

**Comment by Duqino** [comment]
No i removed the health part i think. Its been i while :)
