### ISSUE TITLE
cant spawn caution vehicle

### ISSUE THREAD

**Issue by jamesyyq27** [esx-framework/esx_jobs#90]

**Comment by jamesyyq27** [comment]
SCRIPT ERROR: @esx_jobs/server/main.lua:87: attempt to call a nil value (field 'showNotification')

**Comment by XvenDeR** [comment]
> SCRIPT ERROR: @esx_jobs/server/main.lua:87: attempt to call a nil value (field 'showNotification')

update esx

**Comment by BrakingESX247** [comment]
Not relevant.
