### ISSUE TITLE
Fuel job taking more oil resources 

### ISSUE THREAD

**Issue by CapitalistNick** [esx-framework/esx_jobs#96]
Even after it says you can't carry any more refined oil, it keeps taking oil out of my inventory which is not giving me any more refined oil

**Comment by rheein** [comment]
are you using limit system or weight?

**Comment by CapitalistNick** [comment]
> are you using limit system or weight?

Limit, we have it set so you can carry only 24 of those items each

**Comment by BrakingESX247** [comment]
@CapitalistNick Still having issues with that?
