### ISSUE TITLE
esx_jobs:reporter

### ISSUE THREAD

**Issue by tiger1974** [esx-framework/esx_jobs#97]
When you take the reporter job, it teleports you up into a building with no interior. I looked in ../jobs/reporter.lua but there's no cloakroom info to change to fix these teleport points.

**Comment by Duqino** [comment]
You need a IPL louder too fix it.

https://github.com/ESX-PUBLIC/fivem-ipl

**Comment by BrakingESX247** [comment]
Hello, I believe the previous comment is the solution, if not, open another issue, thank you!
